### ISSUE TITLE
Project doesnt have a good read me

### ISSUE THREAD

**Issue by alceil** [rishimohan/pika#10]
The project doesn't have a good read me and would require one for people to understand what the project is about and hence contribute to it. So I propose to create a good readme.

**Comment by rishimohan** [comment]
@alceil Hi, I've updated the readme to give more context about what, hows and why of the app. Please let me know what you think of it :)

**Comment by alceil** [comment]
I was planning to write your readme something similar to this project of mine. https://github.com/alceil/justpasteit. Would you like something like this?

**Comment by rishimohan** [comment]
@alceil Thanks for that, for now I think it's better to keep it simple since the project isn't that big. I'll definitely take your help when it gets little more attention :)
