### ISSUE TITLE
Resizable inner window viewport

### ISSUE THREAD

**Issue by ehsandeep** [rishimohan/pika#11]
Similar to https://carbon.now.sh

**Comment by rishimohan** [comment]
@ehsandeep Sorry it took some time but custom canvas size is live on pika.style, you can now set custom canvas size and resize canvas using handle bars. Let me know what you think of it :)

![image](https://user-images.githubusercontent.com/14031295/179008707-15f84d8f-af22-444b-9ef6-f1ee07ac8bf7.png)

**Comment by ehsandeep** [comment]
@rishimohan, thanks a lot, this is useful :)
