### ISSUE TITLE
Copy and paste does not work on firefox

### ISSUE THREAD

**Issue by thomassicaud** [rishimohan/pika#12]
Impossible to recover the image with a ctrl + c

**Comment by rishimohan** [comment]
@EternitY-CLaYMan Thanks for reporting the issue. Firefox currently doesn't support copying an image to clipboard programmatically. I'll definitely add it when Firefox provides support for it :)

**Comment by Huluti** [comment]
Hello @rishimohan! 
Firefox supports it behind a hidden pref in about:config.

![image](https://user-images.githubusercontent.com/5782198/182189311-81b41099-cff9-42da-b928-79e8198d6817.png)

Could you enable this in a certain way?
Thanks!

**Comment by rishimohan** [comment]
@Huluti I'll definitely take a look at it again, thanks for sharing.

**Comment by rishimohan** [comment]
@Huluti Sorry for the delay, copy should work on Firefox now when `dom.events.asyncClipboard.clipboardItem` is set to `true` in `about:config`

**Comment by Huluti** [comment]
@rishimohan hey man! you still have some specific Firefox code  :)
![image](https://user-images.githubusercontent.com/5782198/219872220-b8faa0d9-5613-4e96-9046-0286508b0b0c.png)
