### ISSUE TITLE
Watermark can be removed

### ISSUE THREAD

**Issue by Harman-Sandhu** [rishimohan/pika#14]
The watermark can be removed/bypassed by simply removing the code of it with inspect element. In order to prevent this, the watermark should be checked and added when exporting the image.

**Comment by rishimohan** [comment]
@Harman-Sandhu You're right, in fact it's allowed to remove the watermark as of now, not just from the code but also in the options(or when you hover on the watermark). 

Having said that, it's an experiment for now I'll be making changes to it :)
