### ISSUE TITLE
🧩Improvement(Accessibility): Create option to toggle chat widget display

### ISSUE THREAD

**Issue by esau-morais** [rishimohan/pika#15]
### Description

The Intercom widget might be not necessary in some cases and I think it would be great to give the user this control

### Business rule

This feature should probably be only available for pro users (?)

**Comment by esau-morais** [comment]
If this get accepted, I am interested to contribute with this feature

**Comment by rishimohan** [comment]
Hi, chat widget is useful for non-pro users as well. But I can definitely add an option to disable the chat widget in Settings

**Comment by esau-morais** [comment]
I'm able to contribute with this improvement if you want

**Comment by esau-morais** [comment]
This issue was closed due to inactivity.

**Comment by rishimohan** [comment]
@esau-morais Hi, sorry for the delay in adding this. Now you can hide chat widget icon from "Settings > Appearance". For now, it works per session only

<img width="972" alt="image" src="https://user-images.githubusercontent.com/14031295/219590318-e9df9ec3-e140-4b10-ba46-0a3b19753544.png">
