### ISSUE TITLE
Feature Request: Highlight a feature on mockup

### ISSUE THREAD

**Issue by YashsviG** [rishimohan/pika#16]
### Purpose:
To be able to highlight a certain feature/button on the mockup

### HOW:
Highlighting could be done by: 
1. Maginifying effect
2. Pop-out effect

**Comment by rishimohan** [comment]
Hi Yashvi, thanks for the suggestions! Magnifying effect is in roadmap. Any references for pop-out effect? I am assuming it's highlighting a specific part of image with rest of the image dimmed, please correct me if I'm wrong

**Comment by YashsviG** [comment]
Something along those line, it could also be in relation with the maginfying effect where let's say a button is magnified but also has a 3D effect. So something like this:
![image](https://user-images.githubusercontent.com/45160510/199580958-51f75652-871d-449d-b312-ddddcb471baf.png)
This has more examples of similar effect: https://www.istockphoto.com/photo/cartoon-character-hand-holds-smart-phone-gm1321139489-407461760?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_bottom&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fapp-mockup&utm_term=app%20mockup%3A%3A%3A

**Comment by rishimohan** [comment]
This isn't what I imagined when I read the pop-out effect 😅. I mean making a specific part of the image highlight in a 3d way, say button would be a little difficult. I'll explore on this and see if this is something that can be added

**Comment by YashsviG** [comment]
This is just a rough idea of how I imagine this to be implemented (some ideas of how photoshop works)
Have a selection tool --> the user is able to select a certain area --> now you can add various effects to the selected area one could be a 3D effect

**Comment by rishimohan** [comment]
@YashsviG Now you can highlight an area in your image

Here's how you can do that: https://pika.style/articles/add-image-highlight
and here's a quick demo video: https://youtu.be/m6-WQ8OH--M

Let me know what you think :)

**Comment by YashsviG** [comment]
Hey @rishimohan This looks amazing! Thanks for the feature :)
I am hoping to see some magnifying effect, i.e. increase the part of the image highlighted. But this is a step closer :))
I will close this issue!
