### ISSUE TITLE
Ability to completely remove the rounded corners not only from the screenshot, but also from the image

### ISSUE THREAD

**Issue by nibezo** [rishimohan/pika#2]
Example: 

![image](https://user-images.githubusercontent.com/52705623/148104312-aae4f3d5-eecb-47aa-a7bd-a1b7cdc12336.png)

In Telegram (and other messengers) the rounded corners are't visible in full-screen mode. In classic mode all is okay: 

![image](https://user-images.githubusercontent.com/52705623/148104670-8dfbe056-3b82-4c90-9937-cc0cecdb8c06.png)

**Comment by rishimohan** [comment]
Fixed: https://github.com/rishimohan/pika/commit/e4317f4218714d4d008abfbfc61f2cf21fbe7229
