### ISSUE TITLE
First time copy to clip board functionality seems like broken.

### ISSUE THREAD

**Issue by sangameshsomawar** [rishimohan/pika#3]
Tested in both Safari and Chrome browsers.

**Before Fix:**

https://user-images.githubusercontent.com/93119254/148264986-6b913f92-27b8-4e84-8be1-98e3c74d5ea4.mp4

**After Fix:**

https://user-images.githubusercontent.com/93119254/148265021-6c094f43-536a-4636-92bd-104c113372b5.mov

**Solution:** I tried below solution 

<img width="933" alt="Screenshot 2022-01-05 at 11 22 16 PM" src="https://user-images.githubusercontent.com/93119254/148265051-8c19f7c2-7e03-4f88-8834-0d5c404e5517.png">

**Comment by rishimohan** [comment]
Hi @sangameshsomawar, thanks for reporting the issue. The issue was happening because of stale blob value which I thought would be fixed by a setState callback but it didn't. I've sent a new fix in last 2 commits, it should be working fine now 😀
