### ISSUE TITLE
Typo error in color.

### ISSUE THREAD

**Issue by sangameshsomawar** [rishimohan/pika#4]
Detected by CSpell VS code extension 😅

<img width="733" alt="Screenshot 2022-01-08 at 12 13 18 AM" src="https://user-images.githubusercontent.com/93119254/148591542-c9e39503-908d-4f09-b2d0-bc4d8a30cc7d.png">

**Comment by rishimohan** [comment]
Thanks for reporting @sangameshsomawar 👍, gotta check the extension 😃
