### ISSUE TITLE
Losing rounded corners after exporting images.

### ISSUE THREAD

**Issue by zhshch2002** [rishimohan/pika#6]
I downloaded the png file after editing the image on macOS Monterey and Chrome, but the exported file does not contain rounded corners.

**Comment by rishimohan** [comment]
@zhshch2002 Hi, I've added support for controlling rounding corners for the wrapper and screenshots separately. You should be able to export images with rounding corners now. Let me know how it works :)

<img width="1477" alt="2022-01-13 at 12 49" src="https://user-images.githubusercontent.com/14031295/149283776-1d728207-aa98-4e35-b43b-4a0d2a1f9ce4.png">

**Comment by zhshch2002** [comment]
Yes, there are no more issues now. Thank you for making such a concise and useful tool.
