### ISSUE TITLE
Default save filename overwrites previously saved file 

### ISSUE THREAD

**Issue by mnort9** [rishimohan/pika#7]
The default filename is always "pika-1", so if you're creating multiple screenshots you need to change the filename each time so it doesn't overwrite. An easy fix is adding a timestamp to the filename so each save is unique.

**Comment by rishimohan** [comment]
@mnort9 Thanks for reporting, fixed in https://github.com/rishimohan/pika/commit/986ffb8b40e90d6c19dad3b763c178acc6a1c435. Let me know if you have more feedback :)
