### ISSUE TITLE
Button border radius doesnt match shadow border radius?

### ISSUE THREAD

**Issue by jeffjose** [rishimohan/pika#9]
See image.
![image](https://user-images.githubusercontent.com/173044/152845177-b2d1bd34-4fe3-4556-9117-c4e7feade0f0.png)

I'm on Linux running Chrome Version 98.0.4758.80 (Official Build) (64-bit)

**Comment by rishimohan** [comment]
@jeffjose Thanks for reporting, should be fixed now :)
